/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cloudprofilingmonitor;

import de.hpi_web.cloudSim.model.StringConstants;
import java.text.DecimalFormat;

/**
 *
 * @author christoph
 */
public class StatisticsPanel extends javax.swing.JPanel {

    private double webCost;
    private double appCost;
    private double dbCost;
    private int numberOfWebVms;
    private int numberOfAppVms;
    private int numberOfDbVms;
    private double webCPU;
    private double appCPU;
    private double dbCPU;
    private double webMem;
    private double appMem;
    private double dbMem;
    
    private DecimalFormat df;
    
    public StatisticsPanel() {
        initComponents();
        df = new DecimalFormat("#.##");
        df.setMinimumFractionDigits(2);
        df.setMinimumIntegerDigits(2);
    }
    
    public void setNumberOfVms(String tier, int vms) {
        switch (tier) {
            case StringConstants.Tier.WEB: numberOfWebVms = vms; break;
            case StringConstants.Tier.APP: numberOfAppVms = vms; break;
            case StringConstants.Tier.DB: numberOfDbVms = vms; break;
            default: break;
        }
        refresh();
    }
    
    public void setCost(String tier, double cost) {
        switch (tier) {
            case StringConstants.Tier.WEB: webCost = cost; break;
            case StringConstants.Tier.APP: appCost = cost; break;
            case StringConstants.Tier.DB: dbCost = cost; break;
            default: break;
        }
        refresh();
    }
    
    public void setCPUUtilization(String tier, double cpuUtilization) {
        switch (tier) {
            case StringConstants.Tier.WEB: webCPU = cpuUtilization; break;
            case StringConstants.Tier.APP: appCPU = cpuUtilization; break;
            case StringConstants.Tier.DB: dbCPU = cpuUtilization; break;
            default: break;
        }
        refresh();
    }
    public void setMemoryUtilization(String tier, double memUtilization) {
        switch (tier) {
            case StringConstants.Tier.WEB: webMem = memUtilization; break;
            case StringConstants.Tier.APP: appMem = memUtilization; break;
            case StringConstants.Tier.DB: dbMem = memUtilization; break;
            default: break;
        }
        refresh();
    }

    private void refresh() {
        vmCountLabel.setText(Integer.toString(numberOfWebVms + numberOfAppVms + numberOfDbVms));
        cpuLabel.setText(df.format((webCPU + appCPU + dbCPU)/3));
        memLabel.setText(df.format((webMem + appMem + dbMem)/3));
        
        webCostsLabel.setText(df.format(webCost));
        appCostsLabel.setText(df.format(appCost));
        dbCostsLabel.setText(df.format(dbCost));
        totalCostsLabel.setText(df.format(webCost + appCost + dbCost));
        
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vmCountLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        memLabel = new javax.swing.JLabel();
        cpuLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        webCostsLabel = new javax.swing.JLabel();
        appCostsLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dbCostsLabel = new javax.swing.JLabel();
        totalCostsLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        vmCountLabel.setText("0");

        jLabel1.setText("#VMs:");

        jLabel3.setText("CPU Avg:");

        jLabel4.setText("Memory Avg:");

        memLabel.setText("0");

        cpuLabel.setText("0");

        jLabel5.setText("Costs Web:");

        webCostsLabel.setText("0");

        appCostsLabel.setText("0");

        jLabel6.setText("Costs App:");

        jLabel7.setText("Costs DB:");

        dbCostsLabel.setText("0");

        totalCostsLabel.setText("0");

        jLabel8.setText("Costs Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpuLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vmCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(webCostsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(appCostsLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dbCostsLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalCostsLabel)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vmCountLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpuLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(memLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(webCostsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(appCostsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dbCostsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalCostsLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appCostsLabel;
    private javax.swing.JLabel cpuLabel;
    private javax.swing.JLabel dbCostsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel memLabel;
    private javax.swing.JLabel totalCostsLabel;
    private javax.swing.JLabel vmCountLabel;
    private javax.swing.JLabel webCostsLabel;
    // End of variables declaration//GEN-END:variables
}
